<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Name_ctl00ctl00mainContentCon_7609b5</name>
   <tag></tag>
   <elementGuidId>fc5593c1-e72b-4873-9507-421e33c9f9ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_txtCompanyName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_mainContent_ContentPlaceHolder1_txtCompanyName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30040420-e23e-4da4-bd1b-f37a311bd63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$ContentPlaceHolder1$txtCompanyName</value>
      <webElementGuid>d8ec6544-9493-4ef2-b4bf-a6c95cfd3cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a91b5d6d-bf32-49d5-a52c-9e285e61ab6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$ctl00$mainContent$ContentPlaceHolder1$txtCompanyName\',\'\')', 0)</value>
      <webElementGuid>78ef2df9-de60-414a-ada7-da1489eebbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;</value>
      <webElementGuid>b71d22c4-5c7b-453c-91c8-cd836716029e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_mainContent_ContentPlaceHolder1_txtCompanyName</value>
      <webElementGuid>81908bd7-798a-4645-889e-d943032dbe2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-lg</value>
      <webElementGuid>7d0fd28e-875a-4676-95c2-a2e7237cd950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_ContentPlaceHolder1_txtCompanyName&quot;)</value>
      <webElementGuid>61036e40-f8b7-4d55-807b-af024d41795d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_txtCompanyName']</value>
      <webElementGuid>ed316e9a-ea8a-4641-b5fa-adc5d895777e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_mainContent_ContentPlaceHolder1_txtCompanyNamePanel']/input</value>
      <webElementGuid>26bfe82c-e777-48fc-ba61-102d5900ac33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>8170d321-ab99-4910-8a15-63fc8d651a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$mainContent$ContentPlaceHolder1$txtCompanyName' and @type = 'text' and @id = 'ctl00_ctl00_mainContent_ContentPlaceHolder1_txtCompanyName']</value>
      <webElementGuid>555d0bf4-f5ef-40ed-b0db-e79d3030f133</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
