<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_ctl00ctl00mainContentCon_c07fc0</name>
   <tag></tag>
   <elementGuidId>45bcbbc6-9119-4618-a7d2-24d968fde84f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1efe529-f731-4f29-b9b2-c43409c3968e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$ContentPlaceHolder1$txtPhone</value>
      <webElementGuid>a944f90f-41fb-4fdc-82b1-9e12d399f4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone</value>
      <webElementGuid>42d3f59e-210e-4a63-90a1-3a15b9a0b648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0347bf59-4a69-48b9-998a-1000473d1dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>e3f20886-0082-4a1d-807d-d3a31465b750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>intlPhoneInput_ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone.api.setNumber(this.value);</value>
      <webElementGuid>978b350b-4527-4be2-ba0a-4c3099a55769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>93ae6319-0c3c-4d3e-9704-f94d731d786f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>074104 10123</value>
      <webElementGuid>eb3f134d-8806-4b9b-9126-860ae247b42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>38d9eb8a-822c-4ae9-b50d-5e59ca1df677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone&quot;)</value>
      <webElementGuid>5143f191-2d13-437d-9c69-279da8534c0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone']</value>
      <webElementGuid>f0807c92-ce90-442d-a194-c8e6f4063742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone-wrapper']/div/input</value>
      <webElementGuid>a880a113-f59d-461a-a3f6-3cff543d3a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/input</value>
      <webElementGuid>ac681403-4ada-4f8e-a358-75f8528c3703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$mainContent$ContentPlaceHolder1$txtPhone' and @id = 'ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone' and @type = 'tel' and @placeholder = '074104 10123']</value>
      <webElementGuid>52f43acf-b85c-4492-a134-557280c07323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
