<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_nextappmail.com</name>
   <tag></tag>
   <elementGuidId>52f23346-297a-4088-8da9-59db0bbdd486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7186bc4f-6cdb-4508-87d5-34d18a6a411b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail</value>
      <webElementGuid>47a926da-7b39-4e35-bfa0-47302dfb2017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:nextapp@mail.com</value>
      <webElementGuid>aeeb3449-72f3-4761-994f-2439e505ca33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>nextapp@mail.com</value>
      <webElementGuid>bbc96d5e-916f-4445-9484-0276498921db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail&quot;)</value>
      <webElementGuid>a29caee7-fd65-4531-be26-cba5e4fb08e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail']</value>
      <webElementGuid>15f3357a-c986-41a2-9282-1ae1113ef7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00__0']/td[2]/a</value>
      <webElementGuid>f324e4be-0e3a-4045-80b6-0403bdd1602d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'nextapp@mail.com')]</value>
      <webElementGuid>10bbb35a-f830-41de-8f87-a3ee675c0acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[1]/following::a[1]</value>
      <webElementGuid>c85e73f4-6ef2-467d-b361-7ad82c6163c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='W 98568956985'])[1]/following::a[3]</value>
      <webElementGuid>b85dc405-4c89-4d40-91ec-92eb44025b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address:'])[1]/preceding::a[1]</value>
      <webElementGuid>78355c43-2996-449b-9179-6a1d0184d4cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[1]</value>
      <webElementGuid>260ba65e-1925-4b0c-af01-6a1fe6903a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='nextapp@mail.com']/parent::*</value>
      <webElementGuid>0c9a18e1-3589-4c11-abcc-c4286681206e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:nextapp@mail.com')]</value>
      <webElementGuid>48e637e9-a551-43ab-b8c8-42c81f577d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>9b796ceb-c576-46e1-85c8-2e17b1b8a475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail' and @href = 'mailto:nextapp@mail.com' and (text() = 'nextapp@mail.com' or . = 'nextapp@mail.com')]</value>
      <webElementGuid>533a9d97-7280-4a09-8c20-f81aa84fdf91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
