<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Poojaagan.com</name>
   <tag></tag>
   <elementGuidId>20bd8e45-35e9-4ae7-aa15-02db95c38b00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c61f8f6-9c2e-424e-a652-c32ce8c5c7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail</value>
      <webElementGuid>5fc96f8f-95b8-401a-9a14-192eed9ced92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:Pooja@agan.com</value>
      <webElementGuid>73537e19-9820-4c2d-8c68-61063e4496be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pooja@agan.com</value>
      <webElementGuid>0cddf2d1-5c24-4e09-b856-f56aff4f538b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail&quot;)</value>
      <webElementGuid>ea4f5ef6-ab85-41c7-81b2-29ac1641db03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail']</value>
      <webElementGuid>9eada448-9763-4e8b-aa31-673c766a3543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00__0']/td[2]/a</value>
      <webElementGuid>e3680ddb-cd8e-4fc9-b1e9-715aee90d9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pooja@agan.com')]</value>
      <webElementGuid>7754d44b-39ba-42f3-8dfd-e4a61e8a906f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[1]/following::a[1]</value>
      <webElementGuid>9e6a7a6a-719a-4da4-97b4-cc00f73ce69f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::a[1]</value>
      <webElementGuid>b935ad31-24f2-441a-83ed-2b616888c6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address:'])[1]/preceding::a[1]</value>
      <webElementGuid>3adcf7d8-6f36-4b88-85c9-d2115415653c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[1]</value>
      <webElementGuid>81887279-524c-44ad-8968-28feb112ba05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pooja@agan.com']/parent::*</value>
      <webElementGuid>2fe9fd01-6a14-432c-b722-e0cde9853bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:Pooja@agan.com')]</value>
      <webElementGuid>105a0b85-bbeb-4d04-907d-eaf27f991dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>8e3b070e-5991-4853-893d-43ec54eb4817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail' and @href = 'mailto:Pooja@agan.com' and (text() = 'Pooja@agan.com' or . = 'Pooja@agan.com')]</value>
      <webElementGuid>11acec3d-b462-4119-b5cf-45a3b4815e48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
