<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Striven Website_img-circle</name>
   <tag></tag>
   <elementGuidId>2bf47882-793f-4dae-9f7c-309f2ac46018</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_ctl00_mainContent_MainHeader_HeaderSection_imgPicture']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0e31039a-d111-4cc7-b0ae-d8117895732f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-circle</value>
      <webElementGuid>b802e8a2-c0a1-4feb-aab2-ae7291ead7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/no_profile_image.png</value>
      <webElementGuid>9ec50465-c917-473a-88a2-fcb8f88919d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_MainHeader_HeaderSection_imgPicture&quot;)/img[@class=&quot;img-circle&quot;]</value>
      <webElementGuid>4c02af85-553e-464d-9fcb-3d80ba2eb609</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ctl00_mainContent_MainHeader_HeaderSection_imgPicture']/img</value>
      <webElementGuid>e45f4736-df07-4dfe-835c-60cced7c8d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>592b2736-4070-490b-ba86-1e9056b445dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/no_profile_image.png']</value>
      <webElementGuid>9287b9c2-834c-45df-8c7f-760f8f5a954d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
