<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_List</name>
   <tag></tag>
   <elementGuidId>442f6fa4-67ab-4ba3-b73b-2838432b46c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mobile-menu']/ul/li[7]/div/div/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>30c3bbb8-5d24-4ec9-94fc-043981f00993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Tasks/Tasks.aspx?nav=1</value>
      <webElementGuid>2c352df9-6da7-48c9-8bca-b5fb2aa9f955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>List</value>
      <webElementGuid>e1dccb44-29bc-4086-ba4e-9031a2ff1c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile-menu&quot;)/ul[@class=&quot;nav navbar-nav main-menu main-menu-hintview&quot;]/li[@class=&quot;dropdown open&quot;]/div[@class=&quot;dropdown-menu multi-column&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/ul[@class=&quot;multi-column-dropdown&quot;]/li[2]/a[1]</value>
      <webElementGuid>7ab3696a-ddd1-4d52-8104-1c06a56c4296</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobile-menu']/ul/li[7]/div/div/div/ul/li[2]/a</value>
      <webElementGuid>7c31457a-8568-484b-b5e8-dcabfd650b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'List')])[10]</value>
      <webElementGuid>f22a9309-02cc-4367-9e99-dd5c2e81263c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[10]/following::a[1]</value>
      <webElementGuid>21ac4e34-a3b7-469b-9f1b-87bc3a5e7887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BETA'])[3]/following::a[3]</value>
      <webElementGuid>244a9364-c6b6-45e7-9413-6f8dea16fb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dispatch'])[1]/preceding::a[1]</value>
      <webElementGuid>2ded52d1-4cb9-4fa9-835d-9a569393a0e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workload'])[1]/preceding::a[2]</value>
      <webElementGuid>08b149db-1700-4112-9305-c827eeea4ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Tasks/Tasks.aspx?nav=1')]</value>
      <webElementGuid>8202060b-4d8c-422c-a56a-d54da955c9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/div/div/ul/li[2]/a</value>
      <webElementGuid>356b022b-c529-4b60-96fc-3538212edbf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Tasks/Tasks.aspx?nav=1' and (text() = 'List' or . = 'List')]</value>
      <webElementGuid>c94751e3-cb24-4844-ba96-e06e734c5b23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
