<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Striven Website_img-circle</name>
   <tag></tag>
   <elementGuidId>77147002-9a0a-47b6-88cc-4562f1864168</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_ctl00_mainContent_MainHeader_HeaderSection_imgPicture']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>462537d3-22f6-449e-b5c0-a7d423030981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-circle</value>
      <webElementGuid>ed8a9d2f-873b-471b-9b7a-98a3d7dfec5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/no_profile_image.png</value>
      <webElementGuid>f2531df2-36c1-440c-9429-f0299cbf61c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_MainHeader_HeaderSection_imgPicture&quot;)/img[@class=&quot;img-circle&quot;]</value>
      <webElementGuid>7f215778-233a-4391-ac3c-6914a77ca091</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ctl00_mainContent_MainHeader_HeaderSection_imgPicture']/img</value>
      <webElementGuid>25563e0e-31b4-4feb-8333-57863c9e79e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>5e6fdbe0-af06-4524-8bc6-c9727d585f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/no_profile_image.png']</value>
      <webElementGuid>cf79298a-8e72-408c-8d08-f73690476822</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
