<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FIRST NAME_ctl00mainContenttxtFirstName</name>
   <tag></tag>
   <elementGuidId>81cd5783-2349-4d63-a6e1-b853c53a9ac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainContent_txtFirstName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainContent_txtFirstName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4662e126-96ab-4618-8081-a66c690201e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$mainContent$txtFirstName</value>
      <webElementGuid>981d61f8-d211-4e44-8a6c-27510f7d8c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>187a3153-a657-4c80-98c0-5989e04a9589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>6a764c2a-bcb0-4eb7-9f10-f552ef5ce3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainContent_txtFirstName</value>
      <webElementGuid>2f418746-2b23-4685-b226-a7727a319279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-lg</value>
      <webElementGuid>c7f2004f-905d-4dd6-864d-7baf830ed178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name*</value>
      <webElementGuid>2d0492d3-3ee7-4477-a05c-6b8e8d751931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent_txtFirstName&quot;)</value>
      <webElementGuid>ce850d06-547b-467d-a883-cfa83be16e9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainContent_txtFirstName']</value>
      <webElementGuid>ce36e3fe-55f0-4417-abf7-59d0df3169f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent_pnlSignupEntry']/div[2]/div/div[3]/div/input</value>
      <webElementGuid>ad188376-461f-4488-938e-736160b19853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>20c0f7f2-6714-43aa-9bca-9e9792b2b5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$mainContent$txtFirstName' and @type = 'text' and @id = 'mainContent_txtFirstName' and @placeholder = 'First Name*']</value>
      <webElementGuid>e06f24a9-238c-4b86-92db-0db1d5160996</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
