<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EMAIL_ctl00mainContenttxtEmail</name>
   <tag></tag>
   <elementGuidId>3fc729c0-5cb1-43bf-89e7-25893ee27c61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainContent_txtEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainContent_txtEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e69ad38c-ddea-4e7d-81b4-18c393f124ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$mainContent$txtEmail</value>
      <webElementGuid>7e66056d-8ec8-434c-8d39-1fb8be36faf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec7fd4b6-25fb-4018-ac4d-28f437d6dcee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>a731f5ef-6f53-4fe6-8060-e37354ec61c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainContent_txtEmail</value>
      <webElementGuid>885985c3-3ffc-4bdb-b8bd-ba30f8ce0b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-lg</value>
      <webElementGuid>3ab20c69-1bf6-4d3a-a7f5-853241e9f0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Business Email*</value>
      <webElementGuid>37de9af8-bd88-4067-8574-d559be484222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent_txtEmail&quot;)</value>
      <webElementGuid>01958d4f-ab38-4c3a-962b-43342773ca30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainContent_txtEmail']</value>
      <webElementGuid>3a0227cf-70d3-475e-a861-1e56f6be9024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent_pnlSignupEntry']/div[2]/div/div[5]/div/input</value>
      <webElementGuid>7922ea01-8283-44cb-93f8-0a0caeb33c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>1f672f40-b3b2-45e4-80d3-0a7604ee00a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$mainContent$txtEmail' and @type = 'text' and @id = 'mainContent_txtEmail' and @placeholder = 'Business Email*']</value>
      <webElementGuid>e36d3b6a-32a1-43c8-9b80-546fdcca4236</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
