<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign in_ctl00ctl00mainContentmainCont_49a1e1</name>
   <tag></tag>
   <elementGuidId>bf3c154e-2080-4211-ad0e-de5c30eaac9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainContent_mainContent_txtEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainContent_mainContent_txtEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>083546f4-b4f1-4314-a076-c5afc0b5adfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$mainContent$txtEmail</value>
      <webElementGuid>16118f9c-3a5d-4353-806f-5f57db775d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>9a2ef9f4-669e-404c-99c5-fcf0ca6f0049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainContent_mainContent_txtEmail</value>
      <webElementGuid>0339ee1c-124f-443c-9c7a-50ade5524f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>16499f93-2779-4d50-a7b5-fb7160cadfd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>example@domain.com</value>
      <webElementGuid>0de7694a-ffdf-40b4-8650-ee3612f93876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent_mainContent_txtEmail&quot;)</value>
      <webElementGuid>b4c00dc1-617d-4d1e-8e34-6172d2497925</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainContent_mainContent_txtEmail']</value>
      <webElementGuid>a976f009-002e-4002-b9ea-1ede183887de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent_mainContent_pnlMemeberLogIn']/div/div/div/input</value>
      <webElementGuid>0071cd09-7969-47e8-b231-94b1e4978dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>352c5857-89a6-4399-be69-9f564540cfde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$mainContent$mainContent$txtEmail' and @type = 'email' and @id = 'mainContent_mainContent_txtEmail' and @placeholder = 'example@domain.com']</value>
      <webElementGuid>9e77df28-de2b-4aa8-a4f5-ae97b220e5a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
