<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign in_ctl00ctl00mainContentmainCont_755761</name>
   <tag></tag>
   <elementGuidId>f82824d0-648f-4671-a486-9667014b12a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainContent_mainContent_txtPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainContent_mainContent_txtPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1f0f50d-99d9-49c8-9535-61252a40cdb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$mainContent$txtPassword</value>
      <webElementGuid>c90af882-0d2d-4b60-ba58-a76dcc2cab92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>365302be-864b-43c3-9da4-d4ba4638e885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainContent_mainContent_txtPassword</value>
      <webElementGuid>16dfd7cd-cc50-445d-9076-8bec9168cb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a8a92e0c-de6c-44a4-91d9-4e9ccbb45f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>7f3dc5e1-4f6f-49bd-9799-0304457bb37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent_mainContent_txtPassword&quot;)</value>
      <webElementGuid>52a0412c-1fb0-410b-b87c-c47be3d8999e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainContent_mainContent_txtPassword']</value>
      <webElementGuid>82ac374d-6ab8-494d-bedb-9643be0aec17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent_mainContent_pnlMemeberLogIn']/div/div/div[2]/input</value>
      <webElementGuid>7bf6881a-2c5d-4d15-b0cc-d2e4b2edd62d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>ab6f52a3-ba53-41f9-9a2e-015e25e21e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$mainContent$mainContent$txtPassword' and @type = 'password' and @id = 'mainContent_mainContent_txtPassword' and @placeholder = 'Password']</value>
      <webElementGuid>9b7677bf-7b04-4d4d-9075-71536fceb9cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
