<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Close_fa fa-search fa-lg fa-fw</name>
   <tag></tag>
   <elementGuidId>a5525b49-5239-462e-80b6-f567fffd2ed6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tasks-container']/div[2]/ul/li/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-search.fa-lg.fa-fw</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fb955615-2f5d-4edd-a7e1-e8c37b60c703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-search fa-lg fa-fw</value>
      <webElementGuid>b5996481-48fd-4674-a001-aa93b790f0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tasks-container&quot;)/div[@class=&quot;tasks-layout&quot;]/ul[@class=&quot;actions-panel nav&quot;]/li[1]/a[1]/i[@class=&quot;fa fa-search fa-lg fa-fw&quot;]</value>
      <webElementGuid>eb28cc17-6890-454f-b704-6968110ca101</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tasks-container']/div[2]/ul/li/a/i</value>
      <webElementGuid>7d1bd615-1b9e-4c5b-9f60-7a34313214d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/ul/li/a/i</value>
      <webElementGuid>52e06840-204f-495e-b9c2-c214b194b640</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
