<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Task_task-name</name>
   <tag></tag>
   <elementGuidId>75e6a024-4e13-4090-8cb3-e74e9c7ec5b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='task-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#task-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1844e56-760e-46da-b57f-5821231e6fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b3a8ae3-e73f-4619-9d6c-0732906edb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>task-name</value>
      <webElementGuid>4bef77fd-9328-422f-8a3a-7e9a900acaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cec40ef1-8460-46a5-bb48-feac33f6731f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search-param</name>
      <type>Main</type>
      <value>taskName</value>
      <webElementGuid>4ff5cacf-9506-41b2-8e88-f2a814545cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eadd5b84-74d0-44f0-95fc-9f05c48c8385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: { 'data-search-display': window.striven.objectLabels.task + ' Name'}</value>
      <webElementGuid>9468f46d-8c6c-471a-ab6a-cb6570d584c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search-display</name>
      <type>Main</type>
      <value>Task Name</value>
      <webElementGuid>e49789c4-8e0a-49c1-884f-3938cc8872c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-name&quot;)</value>
      <webElementGuid>6a529c18-c872-4e6b-9358-7e8a6df97084</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='task-name']</value>
      <webElementGuid>d755e9da-3fed-4400-b19f-391e94169fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-panel']/div/div[2]/input</value>
      <webElementGuid>6f561dd8-9d23-4ba5-b9e1-b35b26927f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//search-panel-widget/div/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>97665e19-7acb-4d63-b1da-b12cd4ffe3e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'task-name']</value>
      <webElementGuid>d6915acc-70d2-4138-b9fa-ac163c715386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
