<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type_form-control</name>
   <tag></tag>
   <elementGuidId>3fd7f821-6931-43fc-9595-06c66d8fef73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[32]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dropdown.open > input.form-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02f9abdc-6f8e-453d-9bc7-79b2f3fc535a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a2607a86-362d-487b-bb13-9608f545e5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>21e502d6-642d-4155-8db5-683be1f6487d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>milesTypeahead: options, selectedItem:selectedItem, enable:enable, visible:visible, hasFocus:hasFocus</value>
      <webElementGuid>a7874a8a-e0ac-46e3-bb6c-1ce2e57dfa3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>6494d432-7c2a-4154-8628-4b90fc51ab2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Task Types</value>
      <webElementGuid>229113fe-9273-4e37-8e40-70160ea996cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>95a6f697-f5f5-46e3-ba79-128973321593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4e27c6f1-513a-4600-ba95-4d49bf0ed8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tasks-container&quot;)/div[@class=&quot;tasks-layout&quot;]/div[@class=&quot;center-panel hidden-xs hidden-sm&quot;]/div[1]/div[@class=&quot;panel panel-default inline-edit&quot;]/div[@class=&quot;panel-body&quot;]/task-create-component[1]/div[1]/div[@class=&quot;inline-edit&quot;]/div[@class=&quot;form-horizontal&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-11&quot;]/task-type-typeahead-widget[@class=&quot;typeahead-widget&quot;]/div[@class=&quot;dropdown open&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>e4f1066c-12af-47f1-8b72-f818e06e3b11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[32]</value>
      <webElementGuid>49563d5f-e2c3-4143-9525-c0d85f9c24c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tasks-container']/div[2]/div[3]/div/div[4]/div[2]/task-create-component/div/div/div/div/div/task-type-typeahead-widget/div/input</value>
      <webElementGuid>39fa7f44-dda0-4bc4-9270-9648c3383e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//task-type-typeahead-widget/div/input</value>
      <webElementGuid>dde6a4ab-6df2-4a27-b10b-c732d0a77743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search Task Types']</value>
      <webElementGuid>2c536f3c-6bd4-4570-8b59-745d06200085</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
